GROQ_API_KEY = "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"
MODEL_NAME = "gemma2-9b-it"

OPENAI_API_KEY = "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"
MODELNAME = "llama-3.3-70b-versatile"